env:
  commonjs: true
  es2021: true
  node: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 12
rules:
  no-unused-vars: 0
  semi: [2, always, { omitLastInOneLineBlock: true }]
  indent: [warn, 2]
  no-trailing-spaces: warn
  eol-last: [warn, always]
  no-multiple-empty-lines: [warn, { max: 2, maxEOF: 0 }]
  space-infix-ops: warn
  no-multi-spaces: warn