npm run model:create -- --name Attribute --attributes name:string
npm run model:create -- --name BossRaid --attributes tmp:integer
npm run model:create -- --name BossType --attributes name:string
npm run model:create -- --name Boss --attributes level:integer,name:string,description:string,spawnTime:time,timeLimit:time
npm run model:create -- --name CharacterAttribute --attributes value:integer
npm run model:create -- --name CharacterEquipment --attributes tmp:integer
npm run model:create -- --name CharacterItem --attributes amount:integer
npm run model:create -- --name CharacterParty --attributes tmp:integer
npm run model:create -- --name CharacterTitle --attributes isDisplayed:boolean
npm run model:create -- --name Character --attributes name:string,level:integer,exp:integer,money:integer
npm run model:create -- --name Entity --attributes name:string,description:string
npm run model:create -- --name EntityAttribute --attributes value:integer
npm run model:create -- --name EntityType --attributes name:string,description:string
npm run model:create -- --name EquipmentType --attributes name:string,description:string
npm run model:create -- --name ItemAttribute --attributes value:integer
npm run model:create -- --name ItemLocation --attributes tmp:integer
npm run model:create -- --name ItemLoot --attributes tmp:integer
npm run model:create -- --name ItemPlanMaterial --attributes amount:integer
npm run model:create -- --name ItemPlan --attributes name:string,description:string
npm run model:create -- --name ItemType --attributes name:string,description:string
npm run model:create -- --name Item --attributes name:string,description:string,isTradable:boolean
npm run model:create -- --name Location --attributes name:string,description:string,level_unlock:integer
npm run model:create -- --name Loot --attributes exp:integer,money:integer
npm run model:create -- --name MarketItem --attributes money:integer,isAvailable:boolean
npm run model:create -- --name ModifierAttribute --attributes value:float
npm run model:create -- --name Modifier --attributes name:string,description:string,rewardMultiplier:float
npm run model:create -- --name Party --attributes tmp:integer
npm run model:create -- --name Quality --attributes name:string,description:string
npm run model:create -- --name Title --attributes name:string,description:string
npm run model:create -- --name User --attributes discordId:bigint
npm run lint:models